apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: billettkontroll
  namespace: pensjondeployer
  labels:
    team: pensjondeployer
spec:
  image: {{image}}
  port: 8080

  liveness:
    path: "/internal/health/liveness"
    initialDelay: 1
  readiness:
    path: "/internal/health/liveness"
    initialDelay: 1
  startup:
    path: "/internal/health/liveness"
    initialDelay: 1
    failureThreshold: 100
    periodSeconds: 1

  prometheus:
    enabled: false

  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

  ingresses:
    - https://billettkontroll.intern.nav.no

  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom

  env:
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=75.0 -XX:+UseParallelGC"
    - name: SKJERMEDE_PERSONER_URL
      value: "http://skjermede-personer-pip.nom"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "api://prod-gcp.nom.skjermede-personer-pip/.default"
